#!/bin/sh

#------------------------------#
# XDG SPECS AND ~ ORGANIZATION #
#------------------------------#
! [ -d "$HOME/.config" ]              && mkdir "$HOME/.config"
! [ -d "$HOME/.local/bin" ]           && mkdir -p "$HOME/.local/bin"
! [ -d "$HOME/.local/share" ]         && mkdir -p "$HOME/.local/share"
! [ -d "$HOME/.local/backgrounds" ]   && mkdir -p "$HOME/.local/backgrounds"
! [ -d "$HOME/.cache" ]               && mkdir "$HOME/.cache"
! [ -d "$HOME/.cache/tixati" ]        && mkdir "$HOME/.cache/tixati"
! [ -d "$HOME/github" ]               && mkdir "$HOME/github"
! [ -d "$HOME/pix" ]                  && mkdir "$HOME/pix"
! [ -d "$HOME/vids" ]                 && mkdir "$HOME/vids"
! [ -d "$HOME/dox" ]                  && mkdir "$HOME/dox"
! [ -d "$HOME/dwd" ]                  && mkdir "$HOME/dwd"
! [ -d "$HOME/desktop" ]              && mkdir "$HOME/desktop"
! [ -d "$HOME/p2p" ]                  && mkdir "$HOME/p2p"
! [ -d "$HOME/music" ]                && mkdir "$HOME/music"

rm -rf "$HOME/Downloads"
rm -rf "$HOME/Desktop"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

export XDG_DESKTOP_DIR="$HOME/desktop"
export XDG_DOCUMENTS_DIR="$HOME/dox"
export XDG_DOWNLOAD_DIR="$HOME/dwd"
export XDG_MUSIC_DIR="$HOME/music"
export XDG_PICTURES_DIR="$HOME/pix"
export XDG_VIDEOS_DIR="$HOME/vids"

#--------------------#
# PREFERRED PROGRAMS #
#--------------------#
export BROWSER="/usr/bin/firefox"
export DOCUMENT_VIEWER="/usr/bin/zathura"
export EDITOR="/usr/bin/nvim"
export FILE_MANAGER="/usr/bin/lf"
export IMAGE_EDITOR="/usr/bin/gimp"
export IMAGE_VIEWER="/usr/bin/imv"
export MAIL="/usr/bin/mutt"
export PLAYER="/usr/bin/mpv"
export TERMINAL="/usr/bin/alacritty"

#--------------#
# SCRIPTS PATH #
#--------------#
export PATH=$PATH:$HOME/.local/bin

#--------------#
# GOLANG PATHS #
#--------------#
export GOPATH="${HOME}/github/go"
export GOBIN="${HOME}/github/go/bin"
export PATH=$PATH:$GOBIN

#------#
# RUST #
#------#
export CARGO_HOME="${XDG_DATA_HOME:-$HOME/.local}/cargo"

#-----#
# ZSH #
#-----#
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
export HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/history"

#-------------#
# FZF OPTIONS #
#-------------#
export FZF_DEFAULT_OPTS="--layout=reverse --height 60%"

#--------#
# FFMPEG #
#--------#
export FFMPEG_DATADIR="${XDG_CONFIG_HOME:-$HOME/.config}/ffmpeg"

#------#
# GRIM #
#------#
GRIM_DEFAULT_DIR="${XDG_PICTURES_DIR:-$HOME/pix}/screenshots"
mkdir -p "$GRIM_DEFAULT_DIR"

#---------#
# NODE.JS #
#---------#
export NODE_REPL_HISTORY="${XDG_DATA_HOME:-$HOME/.local/share}/node_repl_history"

#-----#
# NVM #
#-----#
export NVM_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/nvm"

#------------#
# POSTGRESQL #
#------------#
mkdir -p "${XDG_CONFIG_HOME-:$HOME/.config}/pg"
mkdir -p "${XDG_CACHE_HOME-:$HOME/.cache}/pg"
export PSQLRC="${XDG_CONFIG_HOME:-$HOME/.config}/pg/psqlrc"
export PSQL_HISTORY="${XDG_CACHE_HOME:-$HOME/.cache}/pg/psql_history"
export PGPASSFILE="${XDG_CONFIG_HOME:-$HOME/.config}/pg/pgpass"
export PGSERVICEFILE="${XDG_CONFIG_HOME-:$HOME/.config}/pg/pg_service.conf"

#-------#
# REDIS #
#-------#
export REDISCLI_HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/redis/rediscli_history"
export REDISCLI_RCFILE="${XDG_CONFIG_HOME:-$HOME/.config}/redis/redisclirc"

#-----#
# GTK #
#-----#
export GTK2_RC_FILES="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-2.0/gtkrc-2.0"
export GTK_THEME=Gruvbox-Material-Dark

#------------#
# QT OPTIONS #
#------------#
export QT_QPA_PLATFORMTHEME=gtk2
# export QT_QPA_PLATFORM="wayland"
export QT_WAYLAND_FORCE_DPI=physical
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1

#--------#
# BEMENU #
#--------#
export BEMENU_BACKEND="wayland"
export BEMENU_OPTS="
 -iw                                  \
--fn  'Source Code Pro Bold 11' \
  -l  10                              \
--tb  #1D2021                         \
--tf  #A89984                         \
--fb  #3C3836                         \
--ff  #928374                         \
--nb  #282828                         \
--nf  #BDAE93                         \
--hb  #282828                         \
--hf  #FABD2F                         \
--sb  #32302F                         \
--sf  #A89984                         \
"

#-----------------#
# FIREFOX OPTIONS #
#-----------------#
# Enable Wayland for Mozilla Firefox
export MOZ_ENABLE_WAYLAND=1

#------#
# JAVA #
#------#
# Wayland Fix for Java Programs
export _JAVA_AWT_WM_NONREPARENTING=1

#---------#
# WAYLAND #
#---------#
export XDG_SESSION_TYPE="wayland"
# export DISPLAY="wayland-0"
# export GDK_BACKEND=wayland
if test -z "${XDG_RUNTIME_DIR}"; then
    export XDG_RUNTIME_DIR=/tmp/${UID}-runtime-dir
    if ! test -d "${XDG_RUNTIME_DIR}"; then
        mkdir "${XDG_RUNTIME_DIR}"
        chmod 0700 "${XDG_RUNTIME_DIR}"
    fi
fi
export WLR_DRM_NO_MODIFIERS=1
# For Waybar Tray
export XDG_CURRENT_DESKTOP=Unity

#------#
# WGET #
#------#
export WGETRC="${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"
[ $(grep -c "hsts-file" "$WGETRC") -gt 0 ] || echo "hsts-file = ${XDG_CACHE_HOME:-$HOME/.cache}/wget-hsts" >> "$WGETRC"

#-----#
# TIG #
#-----#
mkdir -p "${XDG_CONFIG_HOME:-$HOME/.config}/tig"
mkdir -p "${XDG_DATA_HOME:-$HOME/.local/share}/tig"
export TIGRC_USER="${XDG_CONFIG_HOME:-$HOME/.config}/tig/config"

#------------#
# MISC PATHS #
#------------#
export LESSHISTFILE="-"
export PASSWORD_STORE_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/password-store"
export GNUPGHOME="${XDG_DATA_HOME:-$HOME/.local/share}/gnupg"

exec sway
