#!/bin/sh

#------------------------------#
# XDG SPECS AND ~ ORGANIZATION #
#------------------------------#
! [ -d "$HOME/.config" ]              && mkdir "$HOME/.config"
! [ -d "$HOME/.local/bin" ]           && mkdir -p "$HOME/.local/bin"
! [ -d "$HOME/.local/share" ]         && mkdir -p "$HOME/.local/share"
! [ -d "$HOME/.local/backgrounds" ]   && mkdir -p "$HOME/.local/backgrounds"
! [ -d "$HOME/.cache" ]               && mkdir "$HOME/.cache"
! [ -d "$HOME/.cache/tixati" ]        && mkdir "$HOME/.cache/tixati"
! [ -d "$HOME/GitHub" ]               && mkdir "$HOME/GitHub"
! [ -d "$HOME/Pictures" ]                  && mkdir "$HOME/Pictures"
! [ -d "$HOME/Videos" ]                 && mkdir "$HOME/Videos"
! [ -d "$HOME/Documents" ]                  && mkdir "$HOME/Documents"
! [ -d "$HOME/Downloads" ]                  && mkdir "$HOME/Downloads"
! [ -d "$HOME/Desktop" ]              && mkdir "$HOME/Desktop"
! [ -d "$HOME/P2P" ]                  && mkdir "$HOME/P2P"
! [ -d "$HOME/music" ]                && mkdir "$HOME/Music"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

export XDG_DESKTOP_DIR="$HOME/Desktop"
export XDG_DOCUMENTS_DIR="$HOME/Documents"
export XDG_DOWNLOAD_DIR="$HOME/Downloads"
export XDG_MUSIC_DIR="$HOME/Music"
export XDG_PICTURES_DIR="$HOME/Pictures"
export XDG_VIDEOS_DIR="$HOME/Videos"

#--------------------#
# PREFERRED PROGRAMS #
#--------------------#
export BROWSER="/usr/bin/firefox"
export DOCUMENT_VIEWER="/usr/bin/zathura"
export EDITOR="/usr/bin/nvim"
export FILE_MANAGER="/usr/bin/nnn"
export IMAGE_EDITOR="/usr/bin/gimp"
export IMAGE_VIEWER="/usr/bin/sxiv"
export MAIL="/usr/bin/mutt"
export PLAYER="/usr/bin/mpv"
export TERMINAL="/usr/bin/alacritty"

#--------------#
# SCRIPTS PATH #
#--------------#
export PATH=$PATH:$HOME/.local/bin

#--------------#
# GOLANG PATHS #
#--------------#
export GOPATH="${XDG_DATA_DIR:-$HOME/.local/share}/go"
export GOBIN="${XDG_DATA_DIR:-$HOME/.local/share}/go/bin"
export PATH=$PATH:$GOBIN

#----------#
# HUBSTAFF #
#----------#
export HUBSTAFF_PATH="${XDG_DATA_HOME:-$HOME/.local/share}/Hubstaff"
export PATH=$PATH:$HUBSTAFF_PATH

#---------#
# ANDROID #
#---------#
mkdir -p ${XDG_DATA_HOME:-$HOME/.local/share}/android
export ANDROID_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/android"
export ANDROID_SDK_ROOT="${XDG_DATA_HOME:-$HOME/.local/share}/android"
export PATH=$PATH:${ANDROID_SDK_ROOT}/tools
export PATH=$PATH:${ANDROID_SDK_ROOT}/platform-tools

#------#
# RUST #
#------#
export CARGO_HOME="${XDG_DATA_HOME:-$HOME/.local}/cargo"

#-----#
# ZSH #
#-----#
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
export HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/history"

#-------------#
# FZF OPTIONS #
#-------------#
export FZF_DEFAULT_OPTS="--layout=reverse --height 60%"

#--------#
# FFMPEG #
#--------#
export FFMPEG_DATADIR="${XDG_CONFIG_HOME:-$HOME/.config}/ffmpeg"

#---------#
# NODE.JS #
#---------#
export NODE_REPL_HISTORY="${XDG_DATA_HOME:-$HOME/.local/share}/node_repl_history"
export NPM_CONFIG_USERCONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/npm/npmrc"

#-----#
# NVM #
#-----#
export NVM_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/nvm"

#------------#
# POSTGRESQL #
#------------#
mkdir -p "${XDG_CONFIG_HOME-:$HOME/.config}/pg"
mkdir -p "${XDG_CACHE_HOME-:$HOME/.cache}/pg"
export PSQLRC="${XDG_CONFIG_HOME:-$HOME/.config}/pg/psqlrc"
export PSQL_HISTORY="${XDG_CACHE_HOME:-$HOME/.cache}/pg/psql_history"
export PGPASSFILE="${XDG_CONFIG_HOME:-$HOME/.config}/pg/pgpass"
export PGSERVICEFILE="${XDG_CONFIG_HOME-:$HOME/.config}/pg/pg_service.conf"

#-------#
# REDIS #
#-------#
export REDISCLI_HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/redis/rediscli_history"
export REDISCLI_RCFILE="${XDG_CONFIG_HOME:-$HOME/.config}/redis/redisclirc"

#-----#
# GTK #
#-----#
export GTK2_RC_FILES="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-2.0/gtkrc-2.0"
export GTK_THEME=Gruvbox-Material-Dark

#------------#
# QT OPTIONS #
#------------#
export QT_QPA_PLATFORMTHEME=gtk2
# export QT_QPA_PLATFORM="wayland"
# export QT_WAYLAND_FORCE_DPI=physical
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export QT_AUTO_SCREEN_SCALE_FACTOR=0

#------#
# JAVA #
#------#
# Wayland Fix for Java Programs
export _JAVA_AWT_WM_NONREPARENTING=1
export _JAVA_OPTIONS='-Dsun.java2d.opengl=true'
export _JAVA_OPTIONS="${_JAVA_OPTIONS} -Djava.util.prefs.userRoot=${XDG_CONFIG_HOME:-$HOME/.config}/java"
export JDK_JAVA_OPTIONS="-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel"
mkdir -p "${XDG_CONFIG_HOME:-$HOME/.config}/java"

#------#
# WGET #
#------#
export WGETRC="${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"
[ $(grep -c "hsts-file" "$WGETRC") -gt 0 ] || echo "hsts-file = ${XDG_CACHE_HOME:-$HOME/.cache}/wget-hsts" >> "$WGETRC"

#------------#
# MISC PATHS #
#------------#
export LESSHISTFILE="-"
export PASSWORD_STORE_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/password-store"
#export GNUPGHOME="${XDG_DATA_HOME:-$HOME/.local/share}/gnupg"

#--------#
# TIXATI #
#--------#
export TIXATI_USER_DATA_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/tixati"
export TIXATI_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/tixati"

if test -n "$DESKTOP_SESSION"; then
  export GNOME_KEYRING_CONTROL GNOME_KEYRING_PID
  export SSH_AUTH_SOCK
fi

startx
