#! /bin/sh

# start sxhk daemon to handle hotkeys
pgrep -x sxhkd > /dev/null || sxhkd &
[ pgrep sxhkd >/dev/null 2>&1 ] && notify-send -u "Critical" "sxhkd" "sxhkd was not started successfully"

# window attributes
bspc config border_width	2
bspc config window_gap		12

bspc config split_ratio          	0.50
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true

# nodes
bspc config focus_follows_pointer     false

# multiple monitors setup
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true
bspc config merge_overlapping_monitors	true

# pointer
bspc config pointer_modifier mod4

# set monitors for desktop
monitors=$(xrandr | grep -wi connected | wc -l)
BG_DIR="$HOME/.local/share/backgrounds"

if [ $monitors -gt 1 ]; then
  echo "$monitors monitors detected for desktop"
  . $HOME/.local/bin/set-monitors
  
  # monitors selection
  primary=$(xrandr | grep -i primary | awk '{ print $1 }')
  right=$(xrandr | grep -i 1080x1920 | awk '{ print $1 }')

  # number of desktops for multiple monitors
  bspc monitor $primary	-d 1 2 3 4
  bspc monitor $right 	-d 1 2 3 4
  
  # set wallpapers
  if [ -x "$(command -v xwallpaper)" ]; then
    xwallpaper --output "$primary" --zoom ${BG_DIR}/primary.jpg
    xwallpaper --output "$right" --zoom ${BG_DIR}/right.jpg
  fi

  # start polybar
  if ! pgrep -x polybar; then
    export MONITOR="$primary" && SHELL=/bin/zsh polybar -r primary &
    export MONITOR="$right" && SHELL=/bin/zsh polybar -r primary &
  fi
# using a laptop
elif [[ $monitors -eq 1 ]]; then
  echo "$monitors monitors: laptop detected"
  internal=$(xrandr | grep -w connected | awk '{ print $1 }')
  bspc monitor $internal -d 1 2 3 4 5 6 7 8
  bspc config -m $internal window_gap	9
  if [ -x "$(command -v xwallpaper)" ]; then
    xwallpaper --output "$internal" --zoom ${BG_DIR}/primary.jpg
  fi
  # start polybar
  if ! pgrep -x polybar; then
    export MONITOR="$internal" && SHELL=/bin/zsh polybar -r internal & &> /dev/null
  fi
fi

# colorscheme
bspc config normal_border_color			"#4c566a"
bspc config active_border_color			"#1e1e1e"
bspc config focused_border_color		"#5e81ac"
bspc config presel_feedback_color		"#5e81ac"

# programs rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Screenkey manage=off

